#!/usr/bin/python3
import sys


def isprime(x):
    if x < 3 and x > 0:
        return True
    count = 0
    for i in range(2, x):
        if x % i == 0:
            count += 1
    if count > 0:
        return False
    else:
        return True


with open(sys.argv[1], "r") as a_file:
    for line in a_file:
        strip = int(line.strip())
        for i in range(2, strip):
            if strip % i == 0:
                val = int(strip / i)
                print("{}={}*{}".format(strip, val, i))
                break
a_file.close()
