#!/usr/bin/python3
import sys


def g(x1, num):
    return ((x1 ** 2) + 1) % num


def gg(h, j):
    return g(g(h, j), j)


def eculid(a, b):
    while b != 0:
        remainder = a % b
        a = b
        b = remainder
    if a == 1:
        return False
    print(f"{f}={f//a}*{a}")
    return True


with open(sys.argv[1], "r") as a_file:
    f = int(a_file.readline().strip())
    if f < 10:
        for i in range(2, f):
            if f % i == 0:
                val = int(f / i)
                print("{}={}*{}".format(f, val, i))
                break
    else:
        x = 0
        y = 0
        n = 1
        flag = 0
        while n < f:
            if y == 0 and x == 0:
                x = g(x, f)
                y = g(y, f)
            continue
        else:
            x = g(x, f)
            y = gg(y, f)
        z = abs(y - x)
        result = eculid(z, f)
a_file.close()
